<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 14.01.2017
 * Time: 12:29
 */
class DayFactor extends aFactor {
    public $name = 'День';
    public function __construct() {
        $date = new DateTime("this Monday");
        $int = new DateInterval("P1D");
        for ($i = 0; $i < 7; $i ++) {
            $this -> addNewPossibleValue($date -> format("D"));
            $date -> add($int);
        }
    }

    public function checkApplicability(iFactorable $obj) {
        return ($obj instanceof iTimeFactorable);
        //return parent::checkApplicability($obj); // TODO: Change the autogenerated stub
    }
    public function applyCore(iTimeFactorable $obj) {
        return $obj -> getDateTime() -> format("D");
        //return parent::applyCore($obj); // TODO: Change the autogenerated stub
    }
}